version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: rpg_postgres
    restart: always
    environment:
      POSTGRES_DB: rpgapp           
      POSTGRES_USER: postgres       
      POSTGRES_PASSWORD: Tosiapies1  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  

volumes:
  postgres_data:
